RegistrationAndLogin/Controllers/BookingDetailController.cs
using RegistrationAndLogin.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace RegistrationAndLogin.Controllers
{
    [Authorize]
    public class BookingDetailController : Controller
    {
        UserRegistrationEntities6 dbobj = new UserRegistrationEntities6();
        // GET: BookingDetail
        public ActionResult Index()
        {
            using (UserRegistrationEntities6 dBModel = new UserRegistrationEntities6())
            {
                List<BookingDetail> BookingDetail = new List<BookingDetail>();
                BookingDetail = dBModel.BookingDetails.ToList();
                var emailID = Session["EmailID"].ToString().ToLower();
                BookingDetail = BookingDetail.Where(c => c.EmailID.ToLower() == emailID).ToList();
                return View(BookingDetail);
            }
        }

        // GET: BookingDetail/Details/5
        public ActionResult Details(int id)
        {
            using (UserRegistrationEntities6 dBModel = new UserRegistrationEntities6())
            {
                return View(dBModel.BookingDetails.Where(x => x.UserID == id).FirstOrDefault());
            }
        }

        // GET: BookingDetail/Create
        //  [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookingDetail/Create
        [HttpPost]
        public ActionResult Create(BookingDetail bookingDetail)
        {
            try
            {
                using (UserRegistrationEntities6 dBModel = new UserRegistrationEntities6())
                {
                    {

                        var isExist = IsTimeExist(bookingDetail.TimeForBooking, bookingDetail.StylistName, bookingDetail.DateForBooking);
                        if (isExist)
                        {
                            ModelState.AddModelError("Time exist", "Time already exist");
                            return View(bookingDetail);
                        }
                        else
                        {
                            dBModel.BookingDetails.Add(bookingDetail);
                            dBModel.SaveChanges();
                        }
                    }
                    // TODO: Add insert logic here

                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }
        [NonAction]
        public bool IsTimeExist(TimeSpan TimeForBooking, string StylistName, DateTime DateForBooking)
        {
            using (UserRegistrationEntities6 dc = new UserRegistrationEntities6())
            {
                var v = dc.BookingDetails.Where(a => a.TimeForBooking == TimeForBooking && a.StylistName == StylistName && a.DateForBooking == DateForBooking).FirstOrDefault();
                return v != null;
            }
        }
        // GET: BookingDetail/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            using (UserRegistrationEntities6 dBModel = new UserRegistrationEntities6())
            {
                return View(dBModel.BookingDetails.Where(x => x.UserID == id).FirstOrDefault());
            }
        }

        // POST: BookingDetail/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, BookingDetail bookingDetail)
        {
            try
            {
                using (UserRegistrationEntities6 dBModel = new UserRegistrationEntities6())
                {
                    var isExist = IsTimeExist(bookingDetail.TimeForBooking, bookingDetail.StylistName, bookingDetail.DateForBooking);
                    if (isExist)
                    {
                        ModelState.AddModelError("Time exist", "Time already exist");
                        return View(bookingDetail);
                    }
                    else
                    {
                        dBModel.BookingDetails.Add(bookingDetail);
                        dBModel.SaveChanges();
                    }
                    dBModel.Entry(bookingDetail).State = EntityState.Modified;
                    dBModel.SaveChanges();
                }
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: BookingDetail/Delete/5
        public ActionResult Delete(int id)
        {
            using (UserRegistrationEntities6 dBModel = new UserRegistrationEntities6())
            {
                return View(dBModel.BookingDetails.Where(x => x.UserID == id).FirstOrDefault());
            }
        }

        // POST: BookingDetail/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, BookingDetail bookingDetail)
        {
            try
            {
                using (UserRegistrationEntities6 dBModel = new UserRegistrationEntities6())
                {
                    BookingDetail booking = dBModel.BookingDetails.Where(x => x.UserID == id).FirstOrDefault();
                    dBModel.BookingDetails.Remove(bookingDetail);
                    dBModel.SaveChanges();
                }
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

RegistrationAndLogin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MS Salon Art", "Home", "Booking", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Home", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Booking for Spa", "Create", "BookingDetail")</li>
                    <li>@Html.ActionLink("Booking History" , "Index" , "BookingDetail")</li>
                </ul>
                <ul class="nav navbar-right navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li style=" color : white">@User.Identity.Name</li>
                        <li>@Html.ActionLink("Logout", "Logout", "User")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("SignUp", "Registration", "User")</li>
                        <li>@Html.ActionLink("Login", "Login", "User")</li>
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>